"""Added Payment + Ticketon (4 tables)

Revision ID: 2a160be46acb
Revises: f8e405af70d5
Create Date: 2025-09-09 16:04:15.873312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a160be46acb'
down_revision: Union[str, None] = 'f8e405af70d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=256), nullable=False),
    sa.Column('title_kk', sa.String(length=256), nullable=True),
    sa.Column('title_en', sa.String(length=256), nullable=True),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_last', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['payment_transaction_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_id'], ['payment_transaction_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticketon_order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=256), nullable=False),
    sa.Column('title_kk', sa.String(length=256), nullable=True),
    sa.Column('title_en', sa.String(length=256), nullable=True),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_last', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['ticketon_order_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_id'], ['ticketon_order_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=256), nullable=False),
    sa.Column('order', sa.String(length=256), nullable=False),
    sa.Column('mpi_order', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=256), nullable=False),
    sa.Column('merchant', sa.String(length=256), nullable=False),
    sa.Column('language', sa.String(length=256), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=False),
    sa.Column('desc_order', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('backref', sa.String(), nullable=True),
    sa.Column('wtype', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('pre_p_sign', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('res_code', sa.String(length=256), nullable=True),
    sa.Column('res_desc', sa.String(), nullable=True),
    sa.Column('paid_p_sign', sa.String(), nullable=True),
    sa.Column('rev_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('rev_desc', sa.String(), nullable=True),
    sa.Column('cancel_p_sign', sa.String(), nullable=True),
    sa.Column('order_full_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['payment_transaction_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_mpi_order'), 'payment_transactions', ['mpi_order'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order'), 'payment_transactions', ['order'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_type'), 'payment_transactions', ['transaction_type'], unique=False)
    op.create_table('ticketon_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('show', sa.String(length=256), nullable=False),
    sa.Column('seats', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('lang', sa.String(length=256), nullable=False),
    sa.Column('pre_sale', sa.String(length=256), nullable=True),
    sa.Column('sale', sa.String(length=256), nullable=True),
    sa.Column('reservation_id', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expire', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=256), nullable=True),
    sa.Column('pre_tickets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tickets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sale_secury_token', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['ticketon_order_statuses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticketon_orders_pre_sale'), 'ticketon_orders', ['pre_sale'], unique=False)
    op.create_index(op.f('ix_ticketon_orders_reservation_id'), 'ticketon_orders', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_ticketon_orders_sale'), 'ticketon_orders', ['sale'], unique=False)
    op.create_index(op.f('ix_ticketon_orders_sale_secury_token'), 'ticketon_orders', ['sale_secury_token'], unique=False)
    op.create_index(op.f('ix_ticketon_orders_show'), 'ticketon_orders', ['show'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketon_orders_show'), table_name='ticketon_orders')
    op.drop_index(op.f('ix_ticketon_orders_sale_secury_token'), table_name='ticketon_orders')
    op.drop_index(op.f('ix_ticketon_orders_sale'), table_name='ticketon_orders')
    op.drop_index(op.f('ix_ticketon_orders_reservation_id'), table_name='ticketon_orders')
    op.drop_index(op.f('ix_ticketon_orders_pre_sale'), table_name='ticketon_orders')
    op.drop_table('ticketon_orders')
    op.drop_index(op.f('ix_payment_transactions_transaction_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_mpi_order'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_table('ticketon_order_statuses')
    op.drop_table('payment_transaction_statuses')
    # ### end Alembic commands ###
