"""Added YandexAfishaWidgetTicket

Revision ID: 2e1107951546
Revises: 82e793368999
Create Date: 2025-10-30 11:00:34.169765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1107951546'
down_revision: Union[str, None] = '82e793368999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yandex_afisha_widget_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=256), nullable=False),
    sa.Column('title_kk', sa.String(length=256), nullable=True),
    sa.Column('title_en', sa.String(length=256), nullable=True),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('description_kk', sa.String(), nullable=True),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('address_ru', sa.String(length=256), nullable=True),
    sa.Column('address_kk', sa.String(length=256), nullable=True),
    sa.Column('address_en', sa.String(length=256), nullable=True),
    sa.Column('stadium_ru', sa.String(length=256), nullable=True),
    sa.Column('stadium_kk', sa.String(length=256), nullable=True),
    sa.Column('stadium_en', sa.String(length=256), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('yandex_session_id', sa.String(), nullable=False),
    sa.Column('yandex_widget_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['files.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('academy_galleries_file_id_fkey', 'academy_galleries', type_='foreignkey')
    op.drop_constraint('academy_galleries_group_id_fkey', 'academy_galleries', type_='foreignkey')
    op.create_foreign_key(None, 'academy_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'academy_galleries', 'academy_groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('academy_group_students_request_id_fkey', 'academy_group_students', type_='foreignkey')
    op.create_foreign_key(None, 'academy_group_students', 'request_to_academy_groups', ['request_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('academy_materials_group_id_fkey', 'academy_materials', type_='foreignkey')
    op.drop_constraint('academy_materials_file_id_fkey', 'academy_materials', type_='foreignkey')
    op.create_foreign_key(None, 'academy_materials', 'academy_groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'academy_materials', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('booking_field_party_requests_status_id_fkey', 'booking_field_party_requests', type_='foreignkey')
    op.create_foreign_key(None, 'booking_field_party_requests', 'booking_field_party_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('cart_items_variant_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('category_modifications_modification_type_id_fkey', 'category_modifications', type_='foreignkey')
    op.create_foreign_key(None, 'category_modifications', 'modification_types', ['modification_type_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('field_galleries_file_id_fkey', 'field_galleries', type_='foreignkey')
    op.drop_constraint('field_galleries_party_id_fkey', 'field_galleries', type_='foreignkey')
    op.create_foreign_key(None, 'field_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'field_galleries', 'field_parties', ['party_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('payment_transactions_status_id_fkey', 'payment_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'payment_transactions', 'payment_transaction_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('product_galleries_file_id_fkey', 'product_galleries', type_='foreignkey')
    op.drop_constraint('product_galleries_variant_id_fkey', 'product_galleries', type_='foreignkey')
    op.create_foreign_key(None, 'product_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'product_galleries', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('product_order_item_histories_status_id_fkey', 'product_order_item_histories', type_='foreignkey')
    op.create_foreign_key(None, 'product_order_item_histories', 'product_order_item_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('product_order_items_status_id_fkey', 'product_order_items', type_='foreignkey')
    op.drop_constraint('product_order_items_variant_id_fkey', 'product_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'product_order_items', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'product_order_items', 'product_order_item_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('product_orders_status_id_fkey', 'product_orders', type_='foreignkey')
    op.create_foreign_key(None, 'product_orders', 'product_order_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('request_materials_file_id_fkey', 'request_materials', type_='foreignkey')
    op.create_foreign_key(None, 'request_materials', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('ticketon_orders_status_id_fkey', 'ticketon_orders', type_='foreignkey')
    op.create_foreign_key(None, 'ticketon_orders', 'ticketon_order_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'ticketon_orders', type_='foreignkey')
    op.create_foreign_key('ticketon_orders_status_id_fkey', 'ticketon_orders', 'ticketon_order_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'request_materials', type_='foreignkey')
    op.create_foreign_key('request_materials_file_id_fkey', 'request_materials', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'product_orders', type_='foreignkey')
    op.create_foreign_key('product_orders_status_id_fkey', 'product_orders', 'product_order_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'product_order_items', type_='foreignkey')
    op.drop_constraint(None, 'product_order_items', type_='foreignkey')
    op.create_foreign_key('product_order_items_variant_id_fkey', 'product_order_items', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('product_order_items_status_id_fkey', 'product_order_items', 'product_order_item_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'product_order_item_histories', type_='foreignkey')
    op.create_foreign_key('product_order_item_histories_status_id_fkey', 'product_order_item_histories', 'product_order_item_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'product_galleries', type_='foreignkey')
    op.drop_constraint(None, 'product_galleries', type_='foreignkey')
    op.create_foreign_key('product_galleries_variant_id_fkey', 'product_galleries', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('product_galleries_file_id_fkey', 'product_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.create_foreign_key('payment_transactions_status_id_fkey', 'payment_transactions', 'payment_transaction_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'field_galleries', type_='foreignkey')
    op.drop_constraint(None, 'field_galleries', type_='foreignkey')
    op.create_foreign_key('field_galleries_party_id_fkey', 'field_galleries', 'field_parties', ['party_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('field_galleries_file_id_fkey', 'field_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'category_modifications', type_='foreignkey')
    op.create_foreign_key('category_modifications_modification_type_id_fkey', 'category_modifications', 'modification_types', ['modification_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_variant_id_fkey', 'cart_items', 'product_variants', ['variant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'booking_field_party_requests', type_='foreignkey')
    op.create_foreign_key('booking_field_party_requests_status_id_fkey', 'booking_field_party_requests', 'booking_field_party_statuses', ['status_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'academy_materials', type_='foreignkey')
    op.drop_constraint(None, 'academy_materials', type_='foreignkey')
    op.create_foreign_key('academy_materials_file_id_fkey', 'academy_materials', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('academy_materials_group_id_fkey', 'academy_materials', 'academy_groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'academy_group_students', type_='foreignkey')
    op.create_foreign_key('academy_group_students_request_id_fkey', 'academy_group_students', 'request_to_academy_groups', ['request_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'academy_galleries', type_='foreignkey')
    op.drop_constraint(None, 'academy_galleries', type_='foreignkey')
    op.create_foreign_key('academy_galleries_group_id_fkey', 'academy_galleries', 'academy_groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('academy_galleries_file_id_fkey', 'academy_galleries', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_table('yandex_afisha_widget_tickets')
    # ### end Alembic commands ###
