"""Made sex and birthdate nullable

Revision ID: 2f07cd8719dd
Revises: d74b5939b618
Create Date: 2025-09-19 11:35:36.263274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f07cd8719dd'
down_revision: Union[str, None] = 'd74b5939b618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'sex',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
