"""Made (Deleted)  unit_price total_price automatically countable

Revision ID: 2fbf2df29808
Revises: 8088d95ae49e
Create Date: 2025-09-28 12:04:53.147506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbf2df29808'
down_revision: Union[str, None] = '8088d95ae49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'total_price')
    op.drop_column('cart_items', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('unit_price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('total_price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
