"""Made unit_price total_price automatically countable

Revision ID: 419b830b398e
Revises: 2fbf2df29808
Create Date: 2025-09-28 12:05:10.464150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419b830b398e'
down_revision: Union[str, None] = '2fbf2df29808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('unit_price', sa.Numeric(), sa.Computed('(product_price + delta_price)::DOUBLE PRECISION', persisted=True), nullable=False))
    op.add_column('cart_items', sa.Column('total_price', sa.Numeric(), sa.Computed('((product_price + delta_price) * qty)::DOUBLE PRECISION', persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'total_price')
    op.drop_column('cart_items', 'unit_price')
    # ### end Alembic commands ###
