"""Added Nonce to PT

Revision ID: 6c03926333af
Revises: e75e41912263
Create Date: 2025-09-10 17:15:26.504192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c03926333af'
down_revision: Union[str, None] = 'e75e41912263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('nonce', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_payment_transactions_nonce'), 'payment_transactions', ['nonce'], unique=False)
    op.drop_column('ticketon_orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticketon_orders', sa.Column('status', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payment_transactions_nonce'), table_name='payment_transactions')
    op.drop_column('payment_transactions', 'nonce')
    # ### end Alembic commands ###
