"""Made from_city_id nullable

Revision ID: 708d30868be4
Revises: 7caecd3eba98
Create Date: 2025-09-29 10:16:59.463745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708d30868be4'
down_revision: Union[str, None] = '7caecd3eba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_order_items', 'from_city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_order_items', 'from_city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
