"""Deleted Status from ticketon_order

Revision ID: 7c97a14ff678
Revises: 6c03926333af
Create Date: 2025-09-15 13:48:02.338203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c97a14ff678'
down_revision: Union[str, None] = '6c03926333af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
