"""Added order_items_snapshot

Revision ID: 7caecd3eba98
Revises: ec7665c7b257
Create Date: 2025-09-29 10:12:24.233227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7caecd3eba98'
down_revision: Union[str, None] = 'ec7665c7b257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_orders', sa.Column('order_items_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_orders', 'order_items_snapshot')
    # ### end Alembic commands ###
