"""Made USER_ID CASCASE ON DELETE 

Revision ID: 8088d95ae49e
Revises: d665aa90ba34
Create Date: 2025-09-24 09:51:06.265674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8088d95ae49e'
down_revision: Union[str, None] = 'd665aa90ba34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_code_verifications_user_id_fkey', 'user_code_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_code_verifications', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_code_verifications', type_='foreignkey')
    op.create_foreign_key('user_code_verifications_user_id_fkey', 'user_code_verifications', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
