"""Added value to BookingFieldPartyStatus

Revision ID: a215d61ef4a1
Revises: c6da5d58d983
Create Date: 2025-09-30 20:19:32.632867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a215d61ef4a1'
down_revision: Union[str, None] = 'c6da5d58d983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_field_party_statuses', sa.Column('value', sa.String(length=350), nullable=False))
    op.create_index(op.f('ix_booking_field_party_statuses_value'), 'booking_field_party_statuses', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_field_party_statuses_value'), table_name='booking_field_party_statuses')
    op.drop_column('booking_field_party_statuses', 'value')
    # ### end Alembic commands ###
