"""Added TicketonOrderAndPaymentTransactionEntity

Revision ID: d74b5939b618
Revises: 97334c3e0cc6
Create Date: 2025-09-17 19:09:52.466368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74b5939b618'
down_revision: Union[str, None] = '97334c3e0cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticketon_order_and_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketon_order_id', sa.Integer(), nullable=False),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('link_type', sa.String(length=256), nullable=False),
    sa.Column('link_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticketon_order_id'], ['ticketon_orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketon_order_and_payment_transactions')
    # ### end Alembic commands ###
