"""Added show_info to ticketon_order_dto

Revision ID: d78e752c6019
Revises: 7c97a14ff678
Create Date: 2025-09-17 11:17:16.036401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd78e752c6019'
down_revision: Union[str, None] = '7c97a14ff678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticketon_orders', sa.Column('show_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticketon_orders', 'show_info')
    # ### end Alembic commands ###
