"""Added Payment to TicketonOrder

Revision ID: e75e41912263
Revises: 2a160be46acb
Create Date: 2025-09-09 16:09:36.403615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75e41912263'
down_revision: Union[str, None] = '2a160be46acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticketon_orders', sa.Column('payment_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticketon_orders', 'payment_transactions', ['payment_transaction_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticketon_orders', type_='foreignkey')
    op.drop_column('ticketon_orders', 'payment_transaction_id')
    # ### end Alembic commands ###
