from datetime import datetime
from decimal import Decimal
import random

from sqlalchemy.ext.asyncio import AsyncSession

from app.entities import ProductVariantEntity
from app.seeders.base_seeder import BaseSeeder
from app.shared.db_table_constants import AppTableNames
from app.shared.db_value_constants import DbValueConstants


class ProductVariantSeeder(BaseSeeder):
    async def seed(self, session: AsyncSession) -> None:
        product_variants = self.get_data()
        await self.load_seeders(
            ProductVariantEntity, session, AppTableNames.ProductVariantTableName, product_variants
        )

    def get_dev_data(self) -> list[ProductVariantEntity]:
        return [
            # Варианты для Игровой формы Nike Dri-FIT (product_id=1)
            ProductVariantEntity(
                id=1,
                product_id=1,
                image_id=None,
                city_id=None,
                title_ru="Игровая форма Nike Dri-FIT - Красная S",
                title_kk="Nike Dri-FIT ойын формасы - Қызыл S",
                title_en="Nike Dri-FIT Match Kit - Red S",
                value=DbValueConstants.get_value("Игровая форма Nike Dri-FIT - Красная S"),
                sku="NIKE-KIT-DRIFIT-RED-S",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=2,
                product_id=1,
                image_id=None,
                city_id=None,
                title_ru="Игровая форма Nike Dri-FIT - Красная M",
                title_kk="Nike Dri-FIT ойын формасы - Қызыл M",
                title_en="Nike Dri-FIT Match Kit - Red M",
                value=DbValueConstants.get_value("Игровая форма Nike Dri-FIT - Красная M"),
                sku="NIKE-KIT-DRIFIT-RED-M",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=3,
                product_id=1,
                image_id=None,
                city_id=None,
                title_ru="Игровая форма Nike Dri-FIT - Синяя L",
                title_kk="Nike Dri-FIT ойын формасы - Көк L",
                title_en="Nike Dri-FIT Match Kit - Blue L",
                value=DbValueConstants.get_value("Игровая форма Nike Dri-FIT - Синяя L"),
                sku="NIKE-KIT-DRIFIT-BLU-L",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для Тренировочной формы Adidas (product_id=2)
            ProductVariantEntity(
                id=4,
                product_id=2,
                image_id=None,
                city_id=None,
                title_ru="Тренировочная форма Adidas - Черная M",
                title_kk="Adidas жаттығу формасы - Қара M",
                title_en="Adidas Training Kit - Black M",
                value=DbValueConstants.get_value("Тренировочная форма Adidas - Черная M"),
                sku="ADIDAS-TRAIN-BLK-M",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=5,
                product_id=2,
                image_id=None,
                city_id=None,
                title_ru="Тренировочная форма Adidas - Белая L",
                title_kk="Adidas жаттығу формасы - Ақ L",
                title_en="Adidas Training Kit - White L",
                value=DbValueConstants.get_value("Тренировочная форма Adidas - Белая L"),
                sku="ADIDAS-TRAIN-WHT-L",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для Детской футбольной формы (product_id=3)
            ProductVariantEntity(
                id=6,
                product_id=3,
                image_id=None,
                city_id=None,
                title_ru="Детская футбольная форма - 6-8 лет",
                title_kk="Балалар футбол формасы - 6-8 жас",
                title_en="Kids Football Kit - 6-8 years",
                value=DbValueConstants.get_value("Детская футбольная форма - 6-8 лет"),
                sku="KIDS-FOOTBALL-KIT-6-8",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=7,
                product_id=3,
                image_id=None,
                city_id=None,
                title_ru="Детская футбольная форма - 10-12 лет",
                title_kk="Балалар футбол формасы - 10-12 жас",
                title_en="Kids Football Kit - 10-12 years",
                value=DbValueConstants.get_value("Детская футбольная форма - 10-12 лет"),
                sku="KIDS-FOOTBALL-KIT-10-12",
                price_delta=Decimal("500.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=8,
                product_id=3,
                image_id=None,
                city_id=None,
                title_ru="Детская футбольная форма - 14-16 лет",
                title_kk="Балалар футбол формасы - 14-16 жас",
                title_en="Kids Football Kit - 14-16 years",
                value=DbValueConstants.get_value("Детская футбольная форма - 14-16 лет"),
                sku="KIDS-FOOTBALL-KIT-14-16",
                price_delta=Decimal("1000.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для бутс Nike Mercurial (product_id=4)
            ProductVariantEntity(
                id=9,
                product_id=4,
                image_id=None,
                city_id=None,
                title_ru="Бутсы Nike Mercurial - Размер 40",
                title_kk="Nike Mercurial бутсалары - 40 өлшем",
                title_en="Nike Mercurial Football Boots - Size 40",
                value=DbValueConstants.get_value("Бутсы Nike Mercurial - Размер 40"),
                sku="NIKE-MERCURIAL-40",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=10,
                product_id=4,
                image_id=None,
                city_id=None,
                title_ru="Бутсы Nike Mercurial - Размер 42",
                title_kk="Nike Mercurial бутсалары - 42 өлшем",
                title_en="Nike Mercurial Football Boots - Size 42",
                value=DbValueConstants.get_value("Бутсы Nike Mercurial - Размер 42"),
                sku="NIKE-MERCURIAL-42",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=11,
                product_id=4,
                image_id=None,
                city_id=None,
                title_ru="Бутсы Nike Mercurial - Размер 44",
                title_kk="Nike Mercurial бутсалары - 44 өлшем",
                title_en="Nike Mercurial Football Boots - Size 44",
                value=DbValueConstants.get_value("Бутсы Nike Mercurial - Размер 44"),
                sku="NIKE-MERCURIAL-44",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для сороконожек Adidas Copa (product_id=5)
            ProductVariantEntity(
                id=12,
                product_id=5,
                image_id=None,
                city_id=None,
                title_ru="Сороконожки Adidas Copa - Размер 41",
                title_kk="Adidas Copa сороконожкалары - 41 өлшем",
                title_en="Adidas Copa Turf Shoes - Size 41",
                value=DbValueConstants.get_value("Сороконожки Adidas Copa - Размер 41"),
                sku="ADIDAS-COPA-TURF-41",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=13,
                product_id=5,
                image_id=None,
                city_id=None,
                title_ru="Сороконожки Adidas Copa - Размер 43",
                title_kk="Adidas Copa сороконожкалары - 43 өлшем",
                title_en="Adidas Copa Turf Shoes - Size 43",
                value=DbValueConstants.get_value("Сороконожки Adidas Copa - Размер 43"),
                sku="ADIDAS-COPA-TURF-43",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для футзалок Puma Future (product_id=6)
            ProductVariantEntity(
                id=14,
                product_id=6,
                image_id=None,
                city_id=None,
                title_ru="Футзалки Puma Future - Размер 42",
                title_kk="Puma Future футзалкалары - 42 өлшем",
                title_en="Puma Future Futsal Shoes - Size 42",
                value=DbValueConstants.get_value("Футзалки Puma Future - Размер 42"),
                sku="PUMA-FUTURE-FUTSAL-42",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=15,
                product_id=6,
                image_id=None,
                city_id=None,
                title_ru="Футзалки Puma Future - Размер 44",
                title_kk="Puma Future футзалкалары - 44 өлшем",
                title_en="Puma Future Futsal Shoes - Size 44",
                value=DbValueConstants.get_value("Футзалки Puma Future - Размер 44"),
                sku="PUMA-FUTURE-FUTSAL-44",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для мяча FIFA Pro Quality (product_id=7) - размеры
            ProductVariantEntity(
                id=16,
                product_id=7,
                image_id=None,
                city_id=None,
                title_ru="Мяч FIFA Pro Quality - Размер 4",
                title_kk="FIFA Pro Quality добы - 4 өлшем",
                title_en="FIFA Pro Quality Ball - Size 4",
                value=DbValueConstants.get_value("Мяч FIFA Pro Quality - Размер 4"),
                sku="FIFA-PRO-BALL-SIZE4",
                price_delta=Decimal("-1000.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=17,
                product_id=7,
                image_id=None,
                city_id=None,
                title_ru="Мяч FIFA Pro Quality - Размер 5",
                title_kk="FIFA Pro Quality добы - 5 өлшем",
                title_en="FIFA Pro Quality Ball - Size 5",
                value=DbValueConstants.get_value("Мяч FIFA Pro Quality - Размер 5"),
                sku="FIFA-PRO-BALL-SIZE5",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),

            # Варианты для тренировочного мяча Select (product_id=8)
            ProductVariantEntity(
                id=18,
                product_id=8,
                image_id=None,
                city_id=None,
                title_ru="Тренировочный мяч Select - Размер 5",
                title_kk="Select жаттығу добы - 5 өлшем",
                title_en="Select Training Ball - Size 5",
                value=DbValueConstants.get_value("Тренировочный мяч Select - Размер 5"),
                sku="SELECT-TRAIN-BALL-SIZE5",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),

            # Варианты для детского мяча (product_id=9) - цвета
            ProductVariantEntity(
                id=19,
                product_id=9,
                image_id=None,
                city_id=None,
                title_ru="Детский мяч размер 3 - Красный",
                title_kk="Балалар добы 3 өлшем - Қызыл",
                title_en="Kids Ball Size 3 - Red",
                value=DbValueConstants.get_value("Детский мяч размер 3 - Красный"),
                sku="KIDS-BALL-SIZE3-RED",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=20,
                product_id=9,
                image_id=None,
                city_id=None,
                title_ru="Детский мяч размер 3 - Синий",
                title_kk="Балалар добы 3 өлшем - Көк",
                title_en="Kids Ball Size 3 - Blue",
                value=DbValueConstants.get_value("Детский мяч размер 3 - Синий"),
                sku="KIDS-BALL-SIZE3-BLU",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для набора конусов (product_id=10) - количество
            ProductVariantEntity(
                id=21,
                product_id=10,
                image_id=None,
                city_id=None,
                title_ru="Набор конусов тренировочных - 12 шт",
                title_kk="Жаттығу конустары жинағы - 12 дана",
                title_en="Training Cones Set - 12 pcs",
                value=DbValueConstants.get_value("Набор конусов тренировочных - 12 шт"),
                sku="TRAIN-CONES-SET-12",
                price_delta=Decimal("-1000.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=22,
                product_id=10,
                image_id=None,
                city_id=None,
                title_ru="Набор конусов тренировочных - 20 шт",
                title_kk="Жаттығу конустары жинағы - 20 дана",
                title_en="Training Cones Set - 20 pcs",
                value=DbValueConstants.get_value("Набор конусов тренировочных - 20 шт"),
                sku="TRAIN-CONES-SET-20",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),

            # Варианты для лестницы координации (product_id=11) - длина
            ProductVariantEntity(
                id=23,
                product_id=11,
                image_id=None,
                city_id=None,
                title_ru="Лестница для координации - 4 метра",
                title_kk="Үйлестіру сатысы - 4 метр",
                title_en="Coordination Ladder - 4 meters",
                value=DbValueConstants.get_value("Лестница для координации - 4 метра"),
                sku="COORD-LADDER-4M",
                price_delta=Decimal("-1500.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=24,
                product_id=11,
                image_id=None,
                city_id=None,
                title_ru="Лестница для координации - 6 метров",
                title_kk="Үйлестіру сатысы - 6 метр",
                title_en="Coordination Ladder - 6 meters",
                value=DbValueConstants.get_value("Лестница для координации - 6 метров"),
                sku="COORD-LADDER-6M",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),

            # Варианты для щитков Nike (product_id=12) - размеры
            ProductVariantEntity(
                id=25,
                product_id=12,
                image_id=None,
                city_id=None,
                title_ru="Щитки Nike Mercurial Lite - S",
                title_kk="Nike Mercurial Lite қалқандары - S",
                title_en="Nike Mercurial Lite Shin Guards - S",
                value=DbValueConstants.get_value("Щитки Nike Mercurial Lite - S"),
                sku="NIKE-SHIN-MERC-LITE-S",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=26,
                product_id=12,
                image_id=None,
                city_id=None,
                title_ru="Щитки Nike Mercurial Lite - M",
                title_kk="Nike Mercurial Lite қалқандары - M",
                title_en="Nike Mercurial Lite Shin Guards - M",
                value=DbValueConstants.get_value("Щитки Nike Mercurial Lite - M"),
                sku="NIKE-SHIN-MERC-LITE-M",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=27,
                product_id=12,
                image_id=None,
                city_id=None,
                title_ru="Щитки Nike Mercurial Lite - L",
                title_kk="Nike Mercurial Lite қалқандары - L",
                title_en="Nike Mercurial Lite Shin Guards - L",
                value=DbValueConstants.get_value("Щитки Nike Mercurial Lite - L"),
                sku="NIKE-SHIN-MERC-LITE-L",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для перчаток вратаря (product_id=13) - размеры
            ProductVariantEntity(
                id=28,
                product_id=13,
                image_id=None,
                city_id=None,
                title_ru="Перчатки вратаря Adidas Predator - Размер 8",
                title_kk="Adidas Predator қақпашы қолғаптары - 8 өлшем",
                title_en="Adidas Predator Goalkeeper Gloves - Size 8",
                value=DbValueConstants.get_value("Перчатки вратаря Adidas Predator - Размер 8"),
                sku="ADIDAS-GK-PRED-SIZE8",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=29,
                product_id=13,
                image_id=None,
                city_id=None,
                title_ru="Перчатки вратаря Adidas Predator - Размер 9",
                title_kk="Adidas Predator қақпашы қолғаптары - 9 өлшем",
                title_en="Adidas Predator Goalkeeper Gloves - Size 9",
                value=DbValueConstants.get_value("Перчатки вратаря Adidas Predator - Размер 9"),
                sku="ADIDAS-GK-PRED-SIZE9",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=30,
                product_id=13,
                image_id=None,
                city_id=None,
                title_ru="Перчатки вратаря Adidas Predator - Размер 10",
                title_kk="Adidas Predator қақпашы қолғаптары - 10 өлшем",
                title_en="Adidas Predator Goalkeeper Gloves - Size 10",
                value=DbValueConstants.get_value("Перчатки вратаря Adidas Predator - Размер 10"),
                sku="ADIDAS-GK-PRED-SIZE10",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для сумки Nike (product_id=14) - цвета
            ProductVariantEntity(
                id=31,
                product_id=14,
                image_id=None,
                city_id=None,
                title_ru="Сумка спортивная Nike - Черная",
                title_kk="Nike спорт сөмкесі - Қара",
                title_en="Nike Sports Bag - Black",
                value=DbValueConstants.get_value("Сумка спортивная Nike - Черная"),
                sku="NIKE-SPORTS-BAG-BLK",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=32,
                product_id=14,
                image_id=None,
                city_id=None,
                title_ru="Сумка спортивная Nike - Синяя",
                title_kk="Nike спорт сөмкесі - Көк",
                title_en="Nike Sports Bag - Blue",
                value=DbValueConstants.get_value("Сумка спортивная Nike - Синяя"),
                sku="NIKE-SPORTS-BAG-BLU",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),

            # Варианты для повязки капитана (product_id=15) - цвета
            ProductVariantEntity(
                id=33,
                product_id=15,
                image_id=None,
                city_id=None,
                title_ru="Повязка капитана - Красная",
                title_kk="Капитан таңғышы - Қызыл",
                title_en="Captain Armband - Red",
                value=DbValueConstants.get_value("Повязка капитана - Красная"),
                sku="CAPTAIN-ARMBAND-RED",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=True,
            ),
            ProductVariantEntity(
                id=34,
                product_id=15,
                image_id=None,
                city_id=None,
                title_ru="Повязка капитана - Синяя",
                title_kk="Капитан таңғышы - Көк",
                title_en="Captain Armband - Blue",
                value=DbValueConstants.get_value("Повязка капитана - Синяя"),
                sku="CAPTAIN-ARMBAND-BLU",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
            ProductVariantEntity(
                id=35,
                product_id=15,
                image_id=None,
                city_id=None,
                title_ru="Повязка капитана - Желтая",
                title_kk="Капитан таңғышы - Сары",
                title_en="Captain Armband - Yellow",
                value=DbValueConstants.get_value("Повязка капитана - Желтая"),
                sku="CAPTAIN-ARMBAND-YEL",
                price_delta=Decimal("0.00"),
                stock=random.randint(10, 1000),
                is_active=True,
                is_default=False,
            ),
        ]

    def get_prod_data(self) -> list[ProductVariantEntity]:
        return self.get_dev_data()

    def get_dev_updated_data(self) -> None:
        pass

    def get_prod_updated_data(self) -> None:
        pass