class AppTableNames:
    """
    Список наименований таблиц БД
    """

    # TableNames
    RoleTableName = "roles"
    FileTableName = "files"
    PermissionTableName = "permissions"
    RolePermissionTableName = "role_permissions"
    UserTableName = "users"
    UserVerificationTableName = "user_verifications"
    CountryTableName = "countries"
    CityTableName = "cities"
    SportTableName = "sports"
    ProductCategoryTableName = "product_categories"
    ProductTableName = "products"
    ModificationTypeTableName = "modification_types"
    ModificationValueTableName = "modification_values"
    ProductVariantTableName = "product_variants"
    ProductVariantModificationTableName = "product_variant_modifications"
    CategoryModificationTableName = "category_modifications"
    ProductGalleryTableName = "product_galleries"
    FieldTableName = "fields"
    FieldPartyTableName = "field_parties"
    FieldPartyScheduleSettingsTableName = "field_party_schedule_settings"
    FieldPartyScheduleTableName = "field_party_schedules"
    FieldGalleryTableName = "field_galleries"
    AcademyTableName = "academies"
    AcademyGroupTableName = "academy_groups"
    AcademyGroupScheduleTableName = "academy_group_schedules"
    StudentTableName = "students"
    AcademyGroupStudentTableName = "academy_group_students"
    RequestToAcademyGroupTableName = "request_to_academy_groups"
    RequestMaterialTableName = "request_materials"
    AcademyGalleryTableName = "academy_galleries"
    AcademyMaterialTableName = "academy_materials"
    CartTableName = "carts"
    CartItemTableName = "cart_items"
    PaymentTransactionStatusTableName = "payment_transaction_statuses"
    PaymentTransactionsTableName = "payment_transactions"
    TicketonOrderStatusTableName = "ticketon_order_statuses"
    TicketonOrderTableName = "ticketon_orders"
    TicketonOrderAndPaymentTransactionTableName = "ticketon_order_and_payment_transactions"
    UserCodeVerificationTableName = "user_code_verifications"
