from datetime import datetime
from decimal import Decimal

from sqlalchemy.ext.asyncio import AsyncSession

from app.entities import AcademyGroupEntity
from app.seeders.base_seeder import BaseSeeder
from app.shared.db_table_constants import AppTableNames
from app.shared.db_value_constants import DbValueConstants


class AcademyGroupSeeder(BaseSeeder):
    async def seed(self, session: AsyncSession) -> None:
        academy_groups = self.get_data()
        await self.load_seeders(
            AcademyGroupEntity, session, AppTableNames.AcademyGroupTableName, academy_groups
        )

    def get_dev_data(self) -> list[AcademyGroupEntity]:
        return [
            # Группы для Футбольной академии Кайрат (academy_id=1)
            AcademyGroupEntity(
                id=1,
                academy_id=1,
                image_id=None,
                name="Юные футболисты 6-8 лет",
                description_ru="Начальная группа для самых маленьких. Основы владения мячом, координация движений.",
                description_kk="Ең кішкентайларға арналған бастапқы топ. Допты билеу негіздері, қимыл үйлестіруі.",
                description_en="Beginner group for the youngest. Ball control basics, movement coordination.",
                value=DbValueConstants.get_value("Юные футболисты 6-8 лет"),
                min_age=6,
                max_age=8,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=12,
                free_space=8,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),
            AcademyGroupEntity(
                id=2,
                academy_id=1,
                image_id=None,
                name="Футбол 9-12 лет",
                description_ru="Средняя группа. Изучение тактических основ, командная игра.",
                description_kk="Орташа топ. Тактикалық негіздерді үйрену, командалық ойын.",
                description_en="Intermediate group. Learning tactical basics, team play.",
                value=DbValueConstants.get_value("Футбол 9-12 лет"),
                min_age=9,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=15,
                free_space=5,
                price=Decimal("15000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=3,
                academy_id=1,
                image_id=None,
                name="Юниоры 13-16 лет",
                description_ru="Продвинутая группа. Подготовка к соревнованиям, профессиональные навыки.",
                description_kk="Жетілген топ. Жарыстарға дайындық, кәсіби дағдылар.",
                description_en="Advanced group. Competition preparation, professional skills.",
                value=DbValueConstants.get_value("Юниоры 13-16 лет"),
                min_age=13,
                max_age=16,
                is_active=True,
                is_recruiting=False,
                gender=1,  # только мальчики
                booked_space=18,
                free_space=2,
                price=Decimal("18000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=120,
            ),

            # Группы для Баскетбольной академии Астана Тайгерс (academy_id=2)
            AcademyGroupEntity(
                id=4,
                academy_id=2,
                image_id=None,
                name="Мини-баскет 8-10 лет",
                description_ru="Начальное обучение баскетболу на низких кольцах. Развитие моторики.",
                description_kk="Төмен қақпаларда баскетболға бастапқы оқыту. Моториканы дамыту.",
                description_en="Basketball basics on low hoops. Motor skills development.",
                value=DbValueConstants.get_value("Мини-баскет 8-10 лет"),
                min_age=8,
                max_age=10,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=10,
                free_space=6,
                price=Decimal("10000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=5,
                academy_id=2,
                image_id=None,
                name="Баскетбол 11-14 лет",
                description_ru="Основная группа. Изучение правил игры, командные тактики.",
                description_kk="Негізгі топ. Ойын ережелерін үйрену, командалық тактикалар.",
                description_en="Main group. Learning game rules, team tactics.",
                value=DbValueConstants.get_value("Баскетбол 11-14 лет"),
                min_age=11,
                max_age=14,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=14,
                free_space=4,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=120,
            ),
            AcademyGroupEntity(
                id=6,
                academy_id=2,
                image_id=None,
                name="Молодежь 15-20 лет",
                description_ru="Группа для подростков и молодежи. Подготовка к профессиональному уровню.",
                description_kk="Жасөспірімдер мен жастарға арналған топ. Кәсіби деңгейге дайындық.",
                description_en="Teen and youth group. Professional level preparation.",
                value=DbValueConstants.get_value("Молодежь 15-20 лет"),
                min_age=15,
                max_age=20,
                is_active=True,
                is_recruiting=False,
                gender=0,  # для всех
                booked_space=12,
                free_space=0,
                price=Decimal("15000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=150,
            ),

            # Группы для Теннисной академии (academy_id=3)
            AcademyGroupEntity(
                id=7,
                academy_id=3,
                image_id=None,
                name="Теннис для начинающих 5-8 лет",
                description_ru="Первые шаги в теннисе. Работа с мягкими мячами на мини-кортах.",
                description_kk="Теннистегі алғашқы қадамдар. Мини-корттарда жұмсақ доптармен жұмыс.",
                description_en="First steps in tennis. Working with soft balls on mini courts.",
                value=DbValueConstants.get_value("Теннис для начинающих 5-8 лет"),
                min_age=5,
                max_age=8,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=8,
                free_space=4,
                price=Decimal("16000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=45,
            ),
            AcademyGroupEntity(
                id=8,
                academy_id=3,
                image_id=None,
                name="Юниорский теннис 9-14 лет",
                description_ru="Развитие техники ударов, изучение стратегии игры.",
                description_kk="Соққы техникасын дамыту, ойын стратегиясын үйрену.",
                description_en="Developing stroke technique, learning game strategy.",
                value=DbValueConstants.get_value("Юниорский теннис 9-14 лет"),
                min_age=9,
                max_age=14,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=10,
                free_space=2,
                price=Decimal("20000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),

            # Группы для Плавательной школы Дельфин (academy_id=4)
            AcademyGroupEntity(
                id=9,
                academy_id=4,
                image_id=None,
                name="Груднички 3-5 лет",
                description_ru="Начальное плавание для самых маленьких. Преодоление страха воды.",
                description_kk="Ең кішкентайларға арналған бастапқы жүзу. Судан қорқуды жеңу.",
                description_en="Basic swimming for toddlers. Overcoming fear of water.",
                value=DbValueConstants.get_value("Груднички 3-5 лет"),
                min_age=3,
                max_age=5,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=6,
                free_space=4,
                price=Decimal("8000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=30,
            ),
            AcademyGroupEntity(
                id=10,
                academy_id=4,
                image_id=None,
                name="Детское плавание 6-12 лет",
                description_ru="Изучение различных стилей плавания. Подготовка к соревнованиям.",
                description_kk="Әртүрлі жүзу стильдерін үйрену. Жарыстарға дайындық.",
                description_en="Learning different swimming styles. Competition preparation.",
                value=DbValueConstants.get_value("Детское плавание 6-12 лет"),
                min_age=6,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=12,
                free_space=6,
                price=Decimal("10000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=45,
            ),
            AcademyGroupEntity(
                id=11,
                academy_id=4,
                image_id=None,
                name="Взрослые 18+",
                description_ru="Плавание для взрослых. Оздоровительное и спортивное направления.",
                description_kk="Ересектерге арналған жүзу. Сауықтыру және спорттық бағыттар.",
                description_en="Swimming for adults. Wellness and sports directions.",
                value=DbValueConstants.get_value("Взрослые 18+"),
                min_age=18,
                max_age=60,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=8,
                free_space=12,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),

            # Группы для Академии единоборств Барыс (academy_id=5)
            AcademyGroupEntity(
                id=12,
                academy_id=5,
                image_id=None,
                name="Карате 6-10 лет",
                description_ru="Изучение основ карате. Дисциплина и самоконтроль.",
                description_kk="Каратэ негіздерін үйрену. Тәртіп пен өзін-өзі бақылау.",
                description_en="Learning karate basics. Discipline and self-control.",
                value=DbValueConstants.get_value("Карате 6-10 лет"),
                min_age=6,
                max_age=10,
                is_active=True,
                is_recruiting=True,
                gender=1,  # только мальчики
                booked_space=10,
                free_space=5,
                price=Decimal("8000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=13,
                academy_id=5,
                image_id=None,
                name="Дзюдо 11-16 лет",
                description_ru="Борьба дзюдо. Техника бросков и борьбы в партере.",
                description_kk="Дзюдо күресі. Лақтыру техникасы және партерде күрес.",
                description_en="Judo wrestling. Throwing technique and ground fighting.",
                value=DbValueConstants.get_value("Дзюдо 11-16 лет"),
                min_age=11,
                max_age=16,
                is_active=True,
                is_recruiting=False,
                gender=1,  # только мальчики
                booked_space=14,
                free_space=1,
                price=Decimal("10000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=120,
            ),

            # Группы для Гимнастического центра Грация (academy_id=6)
            AcademyGroupEntity(
                id=14,
                academy_id=6,
                image_id=None,
                name="Художественная гимнастика 4-7 лет",
                description_ru="Основы художественной гимнастики. Развитие гибкости и грации.",
                description_kk="Көркем гимнастика негіздері. Иілгіштік пен сұлулықты дамыту.",
                description_en="Rhythmic gymnastics basics. Developing flexibility and grace.",
                value=DbValueConstants.get_value("Художественная гимнастика 4-7 лет"),
                min_age=4,
                max_age=7,
                is_active=True,
                is_recruiting=True,
                gender=2,  # только девочки
                booked_space=12,
                free_space=3,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),
            AcademyGroupEntity(
                id=15,
                academy_id=6,
                image_id=None,
                name="Спортивная гимнастика 8-12 лет",
                description_ru="Спортивная гимнастика. Работа на снарядах, акробатические элементы.",
                description_kk="Спорттық гимнастика. Снарядтарда жұмыс, акробатикалық элементтер.",
                description_en="Artistic gymnastics. Apparatus work, acrobatic elements.",
                value=DbValueConstants.get_value("Спортивная гимнастика 8-12 лет"),
                min_age=8,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=2,  # только девочки
                booked_space=10,
                free_space=5,
                price=Decimal("15000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
        ]

    def get_prod_data(self) -> list[AcademyGroupEntity]:
        return self.get_dev_data()

    def get_dev_updated_data(self) -> None:
        pass

    def get_prod_updated_data(self) -> None:
        pass