from datetime import datetime
from decimal import Decimal

from sqlalchemy.ext.asyncio import AsyncSession

from app.entities import AcademyGroupEntity
from app.seeders.base_seeder import BaseSeeder
from app.shared.db_table_constants import AppTableNames
from app.shared.db_value_constants import DbValueConstants


class AcademyGroupSeeder(BaseSeeder):
    async def seed(self, session: AsyncSession) -> None:
        academy_groups = self.get_data()
        await self.load_seeders(
            AcademyGroupEntity, session, AppTableNames.AcademyGroupTableName, academy_groups
        )

    def get_dev_data(self) -> list[AcademyGroupEntity]:
        return [
            # Группы для Футбольной академии Бауыржан Момышулы (academy_id=1)
            AcademyGroupEntity(
                id=1,
                academy_id=1,
                image_id=None,
                name="Малыши 5-6 лет",
                description_ru="Первые шаги в футболе для самых маленьких. Игровой подход, развитие координации, знакомство с мячом.",
                description_kk="Ең кішкентайларға арналған футболдағы алғашқы қадамдар. Ойын тәсілі, үйлестіруді дамыту, доппен танысу.",
                description_en="First steps in football for the youngest. Playful approach, coordination development, getting familiar with the ball.",
                value=DbValueConstants.get_value("Малыши 5-6 лет"),
                min_age=5,
                max_age=6,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=8,
                free_space=7,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=45,
            ),
            AcademyGroupEntity(
                id=2,
                academy_id=1,
                image_id=None,
                name="Юные футболисты 7-9 лет",
                description_ru="Основы техники владения мячом, простейшие тактические элементы, мини-футбол 5×5.",
                description_kk="Допты билеу техникасының негіздері, ең қарапайым тактикалық элементтер, 5×5 мини-футбол.",
                description_en="Ball control technique basics, simplest tactical elements, 5×5 mini football.",
                value=DbValueConstants.get_value("Юные футболисты 7-9 лет"),
                min_age=7,
                max_age=9,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=14,
                free_space=6,
                price=Decimal("15000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=75,
            ),
            AcademyGroupEntity(
                id=3,
                academy_id=1,
                image_id=None,
                name="Школьники 10-12 лет",
                description_ru="Техническая подготовка, тактические основы, игра на большом поле 7×7, участие в турнирах.",
                description_kk="Техникалық дайындық, тактикалық негіздер, 7×7 үлкен алаңда ойын, турнирлерге қатысу.",
                description_en="Technical training, tactical basics, 7×7 big field play, tournament participation.",
                value=DbValueConstants.get_value("Школьники 10-12 лет"),
                min_age=10,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=18,
                free_space=4,
                price=Decimal("18000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=4,
                academy_id=1,
                image_id=None,
                name="Подростки 13-15 лет",
                description_ru="Продвинутая техника, командная тактика, игра 11×11, физическая подготовка, соревнования.",
                description_kk="Жетілдірілген техника, командалық тактика, 11×11 ойын, дене дайындығы, жарыстар.",
                description_en="Advanced technique, team tactics, 11×11 play, physical training, competitions.",
                value=DbValueConstants.get_value("Подростки 13-15 лет"),
                min_age=13,
                max_age=15,
                is_active=True,
                is_recruiting=False,
                gender=0,  # для всех
                booked_space=22,
                free_space=0,
                price=Decimal("20000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=105,
            ),
            AcademyGroupEntity(
                id=5,
                academy_id=1,
                image_id=None,
                name="Юниоры 16-18 лет",
                description_ru="Предпрофессиональная подготовка, сложная тактика, психологическая подготовка к взрослому футболу.",
                description_kk="Кәсіби алдындағы дайындық, күрделі тактика, ересектер футболына психологиялық дайындық.",
                description_en="Pre-professional training, complex tactics, psychological preparation for adult football.",
                value=DbValueConstants.get_value("Юниоры 16-18 лет"),
                min_age=16,
                max_age=18,
                is_active=True,
                is_recruiting=False,
                gender=0,  # для всех
                booked_space=20,
                free_space=2,
                price=Decimal("25000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=120,
            ),

            # Группы для Футбольной школы Кайрат (academy_id=2)
            AcademyGroupEntity(
                id=6,
                academy_id=2,
                image_id=None,
                name="Кайрат U-8 (6-8 лет)",
                description_ru="Официальная группа младшего возраста ФК Кайрат. Профессиональные тренеры, системный подход.",
                description_kk="ФК Қайраттың кішкентай жастағы ресми тобы. Кәсіби жаттықтырушылар, жүйелік көзқарас.",
                description_en="Official junior group of FC Kairat. Professional coaches, systematic approach.",
                value=DbValueConstants.get_value("Кайрат U-8 (6-8 лет)"),
                min_age=6,
                max_age=8,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=16,
                free_space=4,
                price=Decimal("20000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),
            AcademyGroupEntity(
                id=7,
                academy_id=2,
                image_id=None,
                name="Кайрат U-12 (9-12 лет)",
                description_ru="Средняя группа академии Кайрат. Углубленное изучение техники, первые тактические схемы.",
                description_kk="Қайрат академиясының орташа тобы. Техниканы терең үйрену, алғашқы тактикалық схемалар.",
                description_en="Middle group of Kairat academy. In-depth technique study, first tactical schemes.",
                value=DbValueConstants.get_value("Кайрат U-12 (9-12 лет)"),
                min_age=9,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=20,
                free_space=2,
                price=Decimal("22000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=8,
                academy_id=2,
                image_id=None,
                name="Кайрат U-16 (13-16 лет)",
                description_ru="Старшая группа академии. Подготовка к молодежной команде клуба, серьезные соревнования.",
                description_kk="Академияның үлкен тобы. Клубтың жастар командасына дайындық, маңызды жарыстар.",
                description_en="Senior academy group. Preparation for club's youth team, serious competitions.",
                value=DbValueConstants.get_value("Кайрат U-16 (13-16 лет)"),
                min_age=13,
                max_age=16,
                is_active=True,
                is_recruiting=False,
                gender=1,  # преимущественно мальчики
                booked_space=22,
                free_space=0,
                price=Decimal("28000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=120,
            ),
            AcademyGroupEntity(
                id=9,
                academy_id=2,
                image_id=None,
                name="Кайрат U-19 (17-19 лет)",
                description_ru="Предпрофессиональная группа. Переход в молодежную и основную команду клуба.",
                description_kk="Кәсіби алдындағы топ. Клубтың жастар және негізгі командасына ауысу.",
                description_en="Pre-professional group. Transition to youth and main club team.",
                value=DbValueConstants.get_value("Кайрат U-19 (17-19 лет)"),
                min_age=17,
                max_age=19,
                is_active=True,
                is_recruiting=False,
                gender=1,  # преимущественно мальчики
                booked_space=18,
                free_space=2,
                price=Decimal("30000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=135,
            ),

            # Группы для Детской футбольной академии Алматы (academy_id=3)
            AcademyGroupEntity(
                id=10,
                academy_id=3,
                image_id=None,
                name="Первые шаги 4-5 лет",
                description_ru="Футбольные игры для малышей. Развитие моторики через футбол, социализация.",
                description_kk="Балапандарға арналған футбол ойындары. Футбол арқылы моториканы дамыту, әлеуметтендіру.",
                description_en="Football games for toddlers. Motor skills development through football, socialization.",
                value=DbValueConstants.get_value("Первые шаги 4-5 лет"),
                min_age=4,
                max_age=5,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=10,
                free_space=8,
                price=Decimal("10000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=45,
            ),
            AcademyGroupEntity(
                id=11,
                academy_id=3,
                image_id=None,
                name="Базовая техника 6-9 лет",
                description_ru="Основы футбольной техники для детей. Веселые тренировки с упором на технику.",
                description_kk="Балаларға арналған футбол техникасының негіздері. Техникаға баса назар аудара отырып қуанышты жаттығулар.",
                description_en="Football technique basics for children. Fun training with emphasis on technique.",
                value=DbValueConstants.get_value("Базовая техника 6-9 лет"),
                min_age=6,
                max_age=9,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=16,
                free_space=6,
                price=Decimal("14000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),
            AcademyGroupEntity(
                id=12,
                academy_id=3,
                image_id=None,
                name="Юные таланты 10-13 лет",
                description_ru="Развитие индивидуальных навыков, творческий подход к футболу, турниры.",
                description_kk="Жеке дағдыларды дамыту, футболға шығармашылық көзқарас, турнирлер.",
                description_en="Individual skills development, creative approach to football, tournaments.",
                value=DbValueConstants.get_value("Юные таланты 10-13 лет"),
                min_age=10,
                max_age=13,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=18,
                free_space=4,
                price=Decimal("16000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=75,
            ),
            AcademyGroupEntity(
                id=13,
                academy_id=3,
                image_id=None,
                name="Подготовка к взрослому футболу 14-16 лет",
                description_ru="Переходная группа к взрослому футболу. Серьезная физическая подготовка.",
                description_kk="Ересектер футболына ауысу тобы. Маңызды дене дайындығы.",
                description_en="Transition group to adult football. Serious physical preparation.",
                value=DbValueConstants.get_value("Подготовка к взрослому футболу 14-16 лет"),
                min_age=14,
                max_age=16,
                is_active=True,
                is_recruiting=False,
                gender=0,  # для всех
                booked_space=16,
                free_space=2,
                price=Decimal("18000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),

            # Группы для Школы футбола Астана (academy_id=4)
            AcademyGroupEntity(
                id=14,
                academy_id=4,
                image_id=None,
                name="Астана U-10 (7-10 лет)",
                description_ru="Начальная группа школы Астана. Европейская методика, иностранные тренеры.",
                description_kk="Астана мектебінің бастапқы тобы. Еуропалық әдістеме, шетелдік жаттықтырушылар.",
                description_en="Initial group of Astana school. European methodology, foreign coaches.",
                value=DbValueConstants.get_value("Астана U-10 (7-10 лет)"),
                min_age=7,
                max_age=10,
                is_active=True,
                is_recruiting=True,
                gender=0,  # для всех
                booked_space=18,
                free_space=4,
                price=Decimal("22000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=15,
                academy_id=4,
                image_id=None,
                name="Астана U-14 (11-14 лет)",
                description_ru="Средняя группа. Интенсивные тренировки, современное оборудование, спарринги.",
                description_kk="Орташа топ. Қарқынды жаттығулар, заманауи жабдықтар, серіктестік ойындар.",
                description_en="Middle group. Intensive training, modern equipment, sparring matches.",
                value=DbValueConstants.get_value("Астана U-14 (11-14 лет)"),
                min_age=11,
                max_age=14,
                is_active=True,
                is_recruiting=True,
                gender=1,  # преимущественно мальчики
                booked_space=20,
                free_space=2,
                price=Decimal("26000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=105,
            ),
            AcademyGroupEntity(
                id=16,
                academy_id=4,
                image_id=None,
                name="Астана U-18 (15-18 лет)",
                description_ru="Старшая группа. Подготовка профессиональных игроков, связь с основной командой.",
                description_kk="Үлкен топ. Кәсіби ойыншыларды дайындау, негізгі командамен байланыс.",
                description_en="Senior group. Professional players preparation, connection with main team.",
                value=DbValueConstants.get_value("Астана U-18 (15-18 лет)"),
                min_age=15,
                max_age=18,
                is_active=True,
                is_recruiting=False,
                gender=1,  # преимущественно мальчики
                booked_space=22,
                free_space=0,
                price=Decimal("30000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=135,
            ),
            AcademyGroupEntity(
                id=17,
                academy_id=4,
                image_id=None,
                name="Астана молодежь 19-20 лет",
                description_ru="Молодежная команда. Переход к профессиональному футболу, участие в чемпионатах.",
                description_kk="Жастар командасы. Кәсіби футболға ауысу, чемпионаттарға қатысу.",
                description_en="Youth team. Transition to professional football, championship participation.",
                value=DbValueConstants.get_value("Астана молодежь 19-20 лет"),
                min_age=19,
                max_age=20,
                is_active=True,
                is_recruiting=False,
                gender=1,  # преимущественно мальчики
                booked_space=18,
                free_space=2,
                price=Decimal("35000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=150,
            ),

            # Группы для Женской футбольной академии Алматы (academy_id=5)
            AcademyGroupEntity(
                id=18,
                academy_id=5,
                image_id=None,
                name="Девочки-малышки 5-7 лет",
                description_ru="Футбол для самых маленьких девочек. Игровой подход, развитие координации.",
                description_kk="Ең кішкентай қыздарға арналған футбол. Ойын көзқарасы, үйлестіруді дамыту.",
                description_en="Football for youngest girls. Playful approach, coordination development.",
                value=DbValueConstants.get_value("Девочки-малышки 5-7 лет"),
                min_age=5,
                max_age=7,
                is_active=True,
                is_recruiting=True,
                gender=2,  # только девочки
                booked_space=12,
                free_space=8,
                price=Decimal("12000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=60,
            ),
            AcademyGroupEntity(
                id=19,
                academy_id=5,
                image_id=None,
                name="Юные футболистки 8-12 лет",
                description_ru="Основы женского футбола. Техника, тактика, адаптированная для девочек программа.",
                description_kk="Әйелдер футболының негіздері. Техника, тактика, қыздарға бейімделген бағдарлама.",
                description_en="Women's football basics. Technique, tactics, program adapted for girls.",
                value=DbValueConstants.get_value("Юные футболистки 8-12 лет"),
                min_age=8,
                max_age=12,
                is_active=True,
                is_recruiting=True,
                gender=2,  # только девочки
                booked_space=16,
                free_space=6,
                price=Decimal("15000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=75,
            ),
            AcademyGroupEntity(
                id=20,
                academy_id=5,
                image_id=None,
                name="Девочки-подростки 13-16 лет",
                description_ru="Серьезная подготовка в женском футболе. Участие в турнирах, командная игра.",
                description_kk="Әйелдер футболындағы маңызды дайындық. Турнирлерге қатысу, командалық ойын.",
                description_en="Serious preparation in women's football. Tournament participation, team play.",
                value=DbValueConstants.get_value("Девочки-подростки 13-16 лет"),
                min_age=13,
                max_age=16,
                is_active=True,
                is_recruiting=True,
                gender=2,  # только девочки
                booked_space=18,
                free_space=4,
                price=Decimal("17000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=90,
            ),
            AcademyGroupEntity(
                id=21,
                academy_id=5,
                image_id=None,
                name="Молодые женщины 17-25 лет",
                description_ru="Взрослый женский футбол. Подготовка к национальной сборной, профессиональная карьера.",
                description_kk="Ересек әйелдер футболы. Ұлттық құрамаға дайындық, кәсіби мансап.",
                description_en="Adult women's football. National team preparation, professional career.",
                value=DbValueConstants.get_value("Молодые женщины 17-25 лет"),
                min_age=17,
                max_age=25,
                is_active=True,
                is_recruiting=False,
                gender=2,  # только девочки/женщины
                booked_space=20,
                free_space=2,
                price=Decimal("20000.00"),
                price_per_ru="за месяц",
                price_per_kk="айына",
                price_per_en="per month",
                average_training_time_in_minute=105,
            ),
        ]

    def get_prod_data(self) -> list[AcademyGroupEntity]:
        return self.get_dev_data()

    def get_dev_updated_data(self) -> None:
        pass

    def get_prod_updated_data(self) -> None:
        pass